version: "3.0"

services:
  server:
    image: ghcr.io/memory-io/memory_server:latest
    build: ./packages/memory_server
    ports:
      - "6969:8000"
    environment:
      - MONGO_URI=mongodb+srv://connerlreplogle:poH4LtWfmRQQsXf9@cluster0.mf9snea.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - DATABASE_NAME=memory

  website:
    image: ghcr.io/memory-io/memory_web:latest
    build: ./packages/memory_web
    ports:
      - "3000:3000"
    environment:
      - API_URL=http://localhost:6969
      - ORIGIN=https://m3m0ry.io
      - ANTHROPIC_API_KEY=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
    links:
      - "server:server"
    depends_on:
      - server
    volumes:
      - server-data:/app/data
volumes:
  server-data: {}

    