version: "3.0"

services:
  server:
    build: ./packages/memory_server/
    ports:
      - "8000:8000"
  website:
    build: ./packages/memory_web/
    ports:
      - "3000:3000"
  mongodb:
    image: mongodb/mongodb-community-server
    ports:
      - "27017:27017"