version: "3.0"

services:
  server:
    image: ghcr.io/memory-io/memory_server:latest
    build: 
      context: ./packages/memory_server
      args:
        - DOMAIN=https://m3m0ry.io
    ports:
      - "6969:8000"
    environment:
      - MONGO_URI=
      - DATABASE_NAME=memory
      - DOMAIN=https://m3m0ry.io
      - RUST_LOG=off,memory_server=debug

  website:
    image: ghcr.io/memory-io/memory_web:latest
    build: ./packages/memory_web
    ports:
      - "3000:3000"
    environment:
      - API_URL=http://localhost:6969
      - ORIGIN=https://m3m0ry.io
      - ANTHROPIC_API_KEY=
    links:
      - "server:server"
    depends_on:
      - server
    volumes:
      - server-data:/app/data
volumes:
  server-data: {}

    
