[package]
name = "memory_server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
path = "src/lib.rs"


[dependencies]
actix-cors = "0.7.0"
actix-identity = "0.7.0"
actix-session = { version = "0.9.0", features = ["cookie-session"] }
actix-web = "4.5.1"
anyhow = "1.0.80"
bcrypt = "0.15.0"
bson = { version = "2.9.0", features = ["uuid-1"] }
env_logger = "0.11.2"
futures-util = "0.3.30"
mongodb = "2.8.1"
reqwest = { version = "0.11.24", features = ["json", "cookies"] }
serde = { version = "1.0.196", features = ["derive", "rc"] }
serde_json = "1.0.114"
tokio = { version = "1.36.0", features = ["full"] }
tracing = "0.1.40"
actix-governor = "0.4"
