name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  
  build:
        
    
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mongodb-version: ['latest']
    steps:
    - run: rustup toolchain install stable --profile minimal
    - uses: Swatinem/rust-cache@v2
      with:
        save-if: ${{ github.ref == 'refs/heads/master' }}
    - uses: actions/checkout@v3
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.10.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}
    - name: Build
      working-directory: packages/memory_server
      run: cargo build --verbose
    - name: Run tests
      working-directory: packages/memory_server
      run: cargo test --verbose
